### ISSUE TITLE
执行nodemon app后出现问题

### ISSUE THREAD

**Issue by BunnyLee** [win5do/vue-admin#3]
start.js:247 Refused to frame 'http://ht.www.sogou.com/websearch/features/yun6.jsp?pid=sogou-brse-d2a452ed…98D83EC3B72BB16A05F1BDF&query=Error|http%3A%2F%2Flocalhost%3A9999%2Fapi%2F' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
initIframe @ start.js:247(anonymous function) @ start.js:548
localhost/:1 Refused to load the image 'http://ht.www.sogou.com/images/extsugg/sogoutip.gif' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by BunnyLee** [comment]
QQ1286460303，可以联系吗？我真的很想跑通啊！！

**Comment by win5do** [comment]
加你了，你这个报错我没看懂，用的sougou的图片资源吗？

**Comment by win5do** [comment]
已解决，不是代码的问题，close了
