### ISSUE TITLE
我下载了你的代码但是按照你提示的方式有错误

### ISSUE THREAD

**Issue by daniel-lij** [win5do/vue-admin#6]
1.前端跑起来后ERROR in ./src/js/index.js
Module not found: Error: Can't resolve '../../theme/index.css' in 'D:\person\设计模式\vueTest\vue-fb-d
emo\vue-fb-demo\front-end\src\js'
2.后台nodemon app不能跑起后台
3.希望有时间可以单独问下你相关问题daniel-lij@qq.com

**Comment by win5do** [comment]
fix at commit be8628c39b1ae45936f873028585a5b6f85cbf00
